version: '3'

services:
  bgp-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      bgp-network:
        ipv4_address: 172.20.0.2
    ports:
      - "179:179"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

  bgp-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      bgp-network:
        ipv4_address: 172.20.0.3
    depends_on:
      - bgp-server
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  bgp-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16