FROM golang:1.22

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY ./cmd/server/main.go .

# Build the application
RUN go build -o bgp_server .

# Run the application
CMD ["./bgp_server"]